window.Lessons.lesson8.modules[11] = {
    title: "12. Box Sizing Bug",
    body: `<section class="box-brief">
      <p class="box-kicker">Box Model Lab</p>
      <h3>Break it, then fix it.</h3>
      <p>Toggle border-box to repair the oversized box.</p>
    </section>`,
    svg: ``,
    widgetCode: `<!-- INTERACTIVE MODULE -->
<style>
.box-brief{display:grid;gap:8px;padding:16px;border-radius:8px;background:#111827;border:1px solid rgba(103,232,249,.22);color:#dbeafe}
.box-brief h3{margin:0;color:#f8fafc;font-size:21px}.box-brief p{margin:0;line-height:1.45}.box-kicker{color:#67e8f9;text-transform:uppercase;letter-spacing:.18em;font-size:11px;font-weight:800}
.box-game{display:grid;gap:14px;width:100%;padding:16px;border-radius:8px;background:linear-gradient(180deg,#101827,#172033);border:1px solid rgba(103,232,249,.25);color:#f8fafc;box-shadow:0 18px 38px rgba(0,0,0,.28)}
.box-hud{display:grid;gap:10px}.box-hud-row{display:flex;align-items:center;justify-content:space-between;gap:12px;flex-wrap:wrap}.box-title{font-family:Orbitron,sans-serif;color:#67e8f9;font-size:13px;letter-spacing:.14em;text-transform:uppercase}.box-stat{font:800 12px/1.2 Fira Code,monospace;color:#d1fae5}
.box-meter{height:10px;border-radius:999px;background:#273244;overflow:hidden;border:1px solid rgba(255,255,255,.08)}.box-meter span{display:block;height:100%;width:0;background:linear-gradient(90deg,#22c55e,#67e8f9);transition:width .25s ease}
.box-stage{position:relative;min-height:290px;border-radius:8px;background:#f8fafc;color:#111827;padding:16px;overflow:hidden;display:grid;place-items:center;border:1px solid rgba(255,255,255,.18)}
.box-controls{display:grid;gap:10px}.box-row{display:flex;gap:10px;flex-wrap:wrap;align-items:center;justify-content:center}.box-btn{border:0;border-radius:8px;padding:12px 14px;background:#2563eb;color:white;font-weight:900;cursor:pointer;transition:transform .15s ease,box-shadow .15s ease,background .15s ease}.box-btn:hover,.box-btn.selected{transform:translateY(-1px);box-shadow:0 0 18px rgba(37,99,235,.32)}.box-btn.good{background:#16a34a}.box-btn.bad{background:#dc2626}
.box-slider{width:min(280px,100%);accent-color:#2563eb}.box-feedback{min-height:36px;padding:10px 12px;border-radius:8px;background:#0b1220;border:1px solid rgba(103,232,249,.18);color:#bfdbfe;font-weight:800;text-align:center}.box-feedback.good{color:#86efac;border-color:#22c55e}.box-feedback.bad{color:#fecaca;border-color:#ef4444}
.box-demo{transition:all .2s ease;display:grid;place-items:center;text-align:center;font-weight:900}.target-outline{position:absolute;border:3px dashed #ef4444;border-radius:8px;pointer-events:none}.choice-card{padding:12px;border-radius:8px;background:white;border:2px solid #cbd5e1;cursor:pointer;font-weight:900;min-width:120px;text-align:center;transition:all .18s ease}.choice-card.selected{border-color:#2563eb;box-shadow:0 0 0 4px rgba(37,99,235,.12)}.choice-card.good{border-color:#16a34a;background:#dcfce7}.choice-card.bad{border-color:#dc2626;background:#fee2e2}
.box-zone{min-height:96px;min-width:150px;padding:12px;border-radius:8px;border:2px dashed #94a3b8;background:#eef2ff;display:grid;gap:8px;align-content:start}.box-token{padding:10px;border-radius:8px;background:#0ea5e9;color:white;font-weight:900;text-align:center;cursor:pointer;touch-action:none}.box-confetti{position:absolute;width:8px;height:12px;background:#22c55e;animation:box-pop 720ms ease forwards}@keyframes box-pop{to{transform:translate(var(--x),var(--y)) rotate(540deg);opacity:0}}
@media(max-width:720px){.box-stage{min-height:250px}.box-btn{width:100%}.choice-card{flex:1 1 140px}}
</style>
<div class="box-game" data-box-game data-config='{"marker":"L8_M12_WIN","index":12,"total":20,"kind":"boxSizing","target":{},"prompts":[]}'>
  <div class="box-hud">
    <div class="box-hud-row"><div class="box-title">Module 12 / 20</div><div class="box-stat" data-xp>XP 0</div></div>
    <div class="box-meter"><span data-xp-bar></span></div>
    <div class="box-meter"><span data-progress-bar></span></div>
  </div>
  <div class="box-stage" data-stage></div>
  <div class="box-controls" data-controls></div>
  <div class="box-feedback" data-feedback>Touch the lab to begin.</div>
</div>
<script>
(function(){
  if(!window.Lesson8Game){
    window.Lesson8Game=(function(){
      const storeKey='lesson8-box-xp';
      const state={xp:Number(localStorage.getItem(storeKey)||0)};
      function sound(type){ window.lesson8LastSound=type; try{ const A=window.AudioContext||window.webkitAudioContext; if(!A)return; const ctx=new A(); const osc=ctx.createOscillator(); const gain=ctx.createGain(); osc.frequency.value=type==='success'?740:type==='error'?180:420; gain.gain.value=.035; osc.connect(gain); gain.connect(ctx.destination); osc.start(); setTimeout(function(){osc.stop();ctx.close();},90);}catch(e){} }
      function addXp(amount){ state.xp+=amount; localStorage.setItem(storeKey,String(state.xp)); }
      function setFeedback(root,text,mode){ const el=root.querySelector('[data-feedback]'); el.textContent=text; el.classList.toggle('good',mode==='good'); el.classList.toggle('bad',mode==='bad'); }
      function updateHud(root,cfg){ root.querySelector('[data-xp]').textContent='XP '+state.xp; root.querySelector('[data-xp-bar]').style.width=Math.min(100,state.xp%100)+'%'; root.querySelector('[data-progress-bar]').style.width=Math.round((cfg.index/cfg.total)*100)+'%'; }
      function confetti(root){ const stage=root.querySelector('[data-stage]'); for(let i=0;i<26;i++){ const bit=document.createElement('i'); bit.className='box-confetti'; bit.style.left='50%'; bit.style.top='50%'; bit.style.background=['#22c55e','#67e8f9','#facc15','#fb7185'][i%4]; bit.style.setProperty('--x',(Math.random()*360-180)+'px'); bit.style.setProperty('--y',(Math.random()*-220-40)+'px'); stage.appendChild(bit); setTimeout(()=>bit.remove(),760); } }
      function win(root,cfg,msg){ if(root.dataset.won==='true')return; root.dataset.won='true'; addXp(10); updateHud(root,cfg); setFeedback(root,msg||'Perfect!', 'good'); sound('success'); confetti(root); window.completeModule(cfg.marker); }
      function attempt(root,cfg,msg,bad){ addXp(5); updateHud(root,cfg); setFeedback(root,msg,bad?'bad':''); sound(bad?'error':'click'); }
      const html={
        clickBoxes:function(root,cfg){ stage(root,'<div class="box-row"><div class="choice-card" data-box>Header</div><div class="choice-card" data-box>Image</div><div class="choice-card" data-box>Button</div></div>'); controls(root,'<button class="box-btn" data-check>Scan boxes</button>'); const clicked=new Set(); root.querySelectorAll('[data-box]').forEach(el=>el.onclick=()=>{clicked.add(el.textContent); el.classList.add('selected'); el.style.boxShadow='inset 0 0 0 4px #22c55e'; attempt(root,cfg,'Box revealed: '+el.textContent);}); root.querySelector('[data-check]').onclick=()=>clicked.size>=3?win(root,cfg,'Everything is a box!'):attempt(root,cfg,'Click all three boxes first.',true);},
        borderSlider:function(root,cfg){ stage(root,'<div class="box-demo" data-demo style="width:160px;height:110px;background:#fef08a;border:0 solid #ef4444">I am a box</div>'); controls(root,'<label>Border thickness <input class="box-slider" data-range type="range" min="0" max="16" value="0"></label>'); const demo=root.querySelector('[data-demo]'),r=root.querySelector('[data-range]'); r.oninput=()=>{demo.style.borderWidth=r.value+'px'; attempt(root,cfg,'Border: '+r.value+'px'); if(+r.value>=8)win(root,cfg,'Nice! The invisible box is visible.');};},
        sizeMatch:function(root,cfg){ stage(root,'<div class="target-outline" style="width:180px;height:110px"></div><div class="box-demo" data-demo style="width:80px;height:60px;background:#93c5fd">Resize me</div>'); controls(root,'<label>Width <input class="box-slider" data-w type="range" min="60" max="240" value="80"></label><label>Height <input class="box-slider" data-h type="range" min="40" max="160" value="60"></label>'); const d=root.querySelector('[data-demo]'); function go(){const w=+root.querySelector('[data-w]').value,h=+root.querySelector('[data-h]').value; d.style.width=w+'px'; d.style.height=h+'px'; attempt(root,cfg,w+' x '+h); if(Math.abs(w-180)<=8&&Math.abs(h-110)<=8)win(root,cfg,'Matched the target size!');} root.querySelector('[data-w]').oninput=go; root.querySelector('[data-h]').oninput=go;},
        padding:function(root,cfg){ stage(root,'<div class="box-demo" data-demo style="background:#fb7185;border:3px solid #111827;padding:0;max-width:220px">Text needs breathing room</div>'); controls(root,'<label>Padding <input class="box-slider" data-range type="range" min="0" max="44" value="0"></label>'); const d=root.querySelector('[data-demo]'),r=root.querySelector('[data-range]'); r.oninput=()=>{d.style.padding=r.value+'px'; attempt(root,cfg,'Padding: '+r.value+'px'); if(+r.value>=24)win(root,cfg,'The text can breathe now.');};},
        fourPadding:function(root,cfg){ stage(root,'<div class="box-demo" data-demo style="background:#fde68a;border:3px solid #111827;padding:2px">Move the message away from every wall</div>'); controls(root,['Top','Right','Bottom','Left'].map((n,i)=>'<label>'+n+' <input class="box-slider" data-pad="'+i+'" type="range" min="0" max="40" value="2"></label>').join('')); const d=root.querySelector('[data-demo]'); function go(){const v=[...root.querySelectorAll('[data-pad]')].map(x=>+x.value); d.style.padding=v.map(x=>x+'px').join(' '); attempt(root,cfg,'Padding: '+v.join(' / ')); if(v.every(x=>x>=20))win(root,cfg,'All four sides fixed.');} root.querySelectorAll('[data-pad]').forEach(x=>x.oninput=go);},
        margin:function(root,cfg){ stage(root,'<div class="box-demo" data-a style="width:120px;height:70px;background:#14b8a6;color:white">Box 1</div><div class="box-demo" data-b style="width:120px;height:70px;background:#f97316;color:white;margin-top:-26px">Box 2</div>'); controls(root,'<label>Margin <input class="box-slider" data-range type="range" min="0" max="60" value="0"></label>'); const b=root.querySelector('[data-b]'),r=root.querySelector('[data-range]'); r.oninput=()=>{b.style.marginTop=r.value+'px'; attempt(root,cfg,'Outer space: '+r.value+'px'); if(+r.value>=30)win(root,cfg,'Boxes separated with margin.');};},
        center:function(root,cfg){ stage(root,'<div style="width:100%;background:#e2e8f0;padding:14px"><div class="box-demo" data-demo style="width:150px;height:80px;background:#f9a8d4">Center me</div></div>'); controls(root,'<button class="box-btn" data-choice="float">float:left</button><button class="box-btn" data-choice="auto">margin: 0 auto</button><button class="box-btn" data-choice="pad">padding: 40px</button>'); root.querySelectorAll('[data-choice]').forEach(btn=>btn.onclick=()=>{ if(btn.dataset.choice==='auto'){root.querySelector('[data-demo]').style.margin='0 auto'; btn.classList.add('good'); win(root,cfg,'Centered with auto margins.');} else {btn.classList.add('bad'); attempt(root,cfg,'Try the rule that splits left and right space.',true);} });},
        decide:function(root,cfg){ stage(root,'<div class="box-row"><div class="choice-card" data-prompt>Where does padding add space?</div></div>'); controls(root,'<button class="box-btn" data-a="inside">Inside</button><button class="box-btn" data-a="outside">Outside</button>'); let q=0; const qs=[['Padding adds space...','inside'],['Margin pushes other boxes...','outside'],['Text breathing room is...','inside'],['Space between boxes is...','outside']]; function paint(){root.querySelector('[data-prompt]').textContent=qs[q][0];} root.querySelectorAll('[data-a]').forEach(b=>b.onclick=()=>{ if(b.dataset.a===qs[q][1]){attempt(root,cfg,'Nice!'); q++; if(q>=qs.length)win(root,cfg,'Inside vs outside mastered.'); else paint();}else attempt(root,cfg,'Try the other side.',true);}); paint();},
        borderStyle:function(root,cfg){ stage(root,'<div class="box-demo" data-demo style="width:180px;height:110px;background:#dcfce7;border:5px solid #111827">Pick a border</div>'); controls(root,'<button class="box-btn" data-style="solid">solid</button><button class="box-btn" data-style="dashed">dashed</button><button class="box-btn" data-style="dotted">dotted</button>'); root.querySelectorAll('[data-style]').forEach(b=>b.onclick=()=>{root.querySelector('[data-demo]').style.borderStyle=b.dataset.style; attempt(root,cfg,b.dataset.style+' border'); if(b.dataset.style==='dashed')win(root,cfg,'Dashed border activated.');});},
        radius:function(root,cfg){ stage(root,'<div class="box-demo" data-demo style="width:170px;height:110px;background:#38bdf8;border-radius:0">Round me</div>'); controls(root,'<label>Radius <input class="box-slider" data-range type="range" min="0" max="60" value="0"></label>'); const d=root.querySelector('[data-demo]'),r=root.querySelector('[data-range]'); r.oninput=()=>{d.style.borderRadius=r.value+'px'; attempt(root,cfg,'Radius: '+r.value+'px'); if(+r.value>=30)win(root,cfg,'Corners are smooth.');};},
        circle:function(root,cfg){ stage(root,'<div class="box-demo" data-demo style="width:120px;height:120px;background:#ef4444;border-radius:0"></div>'); controls(root,'<label>Radius % <input class="box-slider" data-range type="range" min="0" max="50" value="0"></label>'); const d=root.querySelector('[data-demo]'),r=root.querySelector('[data-range]'); r.oninput=()=>{d.style.borderRadius=r.value+'%'; attempt(root,cfg,'Radius: '+r.value+'%'); if(+r.value===50)win(root,cfg,'Perfect circle.');};},
        boxSizing:function(root,cfg){ stage(root,'<div style="width:230px;border:3px dashed #ef4444;padding:4px"><div class="box-demo" data-demo style="width:200px;padding:50px;background:#a78bfa;box-sizing:content-box">Too wide</div></div>'); controls(root,'<button class="box-btn" data-fix>Toggle border-box</button>'); root.querySelector('[data-fix]').onclick=()=>{root.querySelector('[data-demo]').style.boxSizing='border-box'; root.querySelector('[data-demo]').textContent='Fixed width'; win(root,cfg,'border-box fixed the bug.');};},
        blockInline:function(root,cfg){ stage(root,'<div class="box-row"><div class="box-zone"><strong>Block line</strong><div class="box-token" data-token="div">div</div><div class="box-token" data-token="p">p</div></div><div class="box-zone"><strong>Inline row</strong><div class="box-token" data-token="span">span</div><div class="box-token" data-token="a">a</div></div></div>'); controls(root,'<button class="box-btn" data-check>Check layout</button>'); root.querySelector('[data-check]').onclick=()=>win(root,cfg,'Block and inline sorted.');},
        inlineBlock:function(root,cfg){ stage(root,'<div class="box-row" data-row><div class="box-demo" style="width:90px;height:80px;background:#bbf7d0;display:block">1</div><div class="box-demo" style="width:90px;height:80px;background:#bfdbfe;display:block">2</div><div class="box-demo" style="width:90px;height:80px;background:#fecaca;display:block">3</div></div>'); controls(root,'<button class="box-btn" data-fix>Use inline-block</button>'); root.querySelector('[data-fix]').onclick=()=>{root.querySelectorAll('.box-demo').forEach(x=>x.style.display='inline-grid'); win(root,cfg,'Side-by-side puzzle solved.');};},
        timedQuiz:function(root,cfg){ let q=0,score=0,time=20,timer; const qs=cfg.prompts; stage(root,'<div class="choice-card" data-question></div>'); controls(root,'<div class="box-row" data-answers></div><div class="box-stat" data-time>20s</div>'); function paint(){root.querySelector('[data-question]').textContent=qs[q].q; root.querySelector('[data-answers]').innerHTML=qs[q].a.map((x,i)=>'<button class="box-btn" data-i="'+i+'">'+x+'</button>').join(''); root.querySelectorAll('[data-i]').forEach(b=>b.onclick=()=>{ if(+b.dataset.i===qs[q].c){score++; attempt(root,cfg,'Correct.');}else attempt(root,cfg,'Missed it. Keep going.',true); q++; if(q>=qs.length)win(root,cfg,'Quiz cleared: '+score+'/'+qs.length); else paint();});} timer=setInterval(()=>{time--; const el=root.querySelector('[data-time]'); if(el)el.textContent=time+'s'; if(time<=0){clearInterval(timer); if(q<qs.length)attempt(root,cfg,'Time is up. Answer the rest to finish.');}},1000); paint();},
        shorthand:function(root,cfg){ const order=['top','right','bottom','left']; let step=0; stage(root,'<div class="box-demo" style="background:#fed7aa;border:3px solid #111827;padding:10px 20px 30px 40px">10 20 30 40</div>'); controls(root,order.map(x=>'<button class="box-btn" data-side="'+x+'">'+x+'</button>').join('')); root.querySelectorAll('[data-side]').forEach(b=>b.onclick=()=>{ if(b.dataset.side===order[step]){b.classList.add('good'); step++; attempt(root,cfg,'Clockwise.'); if(step===4)win(root,cfg,'Top, right, bottom, left decoded.');}else attempt(root,cfg,'Follow the clock.',true);});},
        transparent:function(root,cfg){ stage(root,'<div class="box-demo" data-demo style="width:130px;height:100px;background:#fde68a;border:10px solid #111827">Ghost box</div><div style="margin-top:12px;color:#334155">It still occupies space.</div>'); controls(root,'<button class="box-btn" data-bg>Make background transparent</button><button class="box-btn" data-border>Make border transparent</button>'); const done={bg:false,border:false},d=root.querySelector('[data-demo]'); root.querySelector('[data-bg]').onclick=()=>{done.bg=true; d.style.background='transparent'; attempt(root,cfg,'Background vanished.'); if(done.border)win(root,cfg,'Invisible, but still a box.');}; root.querySelector('[data-border]').onclick=()=>{done.border=true; d.style.borderColor='transparent'; attempt(root,cfg,'Border vanished.'); if(done.bg)win(root,cfg,'Invisible, but still a box.');};},
        finalCard:function(root,cfg){ stage(root,'<div class="box-demo" data-demo style="width:230px;background:#ffffff;color:#111827;padding:4px;margin:0;border:0 solid #06b6d4;border-radius:0;box-shadow:0 10px 24px rgba(0,0,0,.16)"><strong>Nova Coder</strong><p>Box model badge</p></div>'); controls(root,'<label>Padding <input class="box-slider" data-pad type="range" min="0" max="28" value="4"></label><label>Margin <input class="box-slider" data-mar type="range" min="0" max="40" value="0"></label><label>Radius <input class="box-slider" data-rad type="range" min="0" max="24" value="0"></label><label>Border <input class="box-slider" data-bor type="range" min="0" max="6" value="0"></label>'); const d=root.querySelector('[data-demo]'); function go(){const p=+root.querySelector('[data-pad]').value,m=+root.querySelector('[data-mar]').value,r=+root.querySelector('[data-rad]').value,b=+root.querySelector('[data-bor]').value; d.style.padding=p+'px';d.style.margin=m+'px';d.style.borderRadius=r+'px';d.style.borderWidth=b+'px'; attempt(root,cfg,'Build score updating.'); if(p>=18&&m>=18&&r>=12&&b>=2)win(root,cfg,'Final card complete.');} root.querySelectorAll('input').forEach(x=>x.oninput=go);}
      };
      function stage(root,content){root.querySelector('[data-stage]').innerHTML=content}
      function controls(root,content){root.querySelector('[data-controls]').innerHTML=content}
      function init(root){ const cfg=JSON.parse(root.dataset.config); updateHud(root,cfg); setFeedback(root,'See it. Touch it. Fix it. Win.',''); const fn=html[cfg.kind]; if(fn)fn(root,cfg); }
      return {init:init};
    })();
  }
  document.querySelectorAll('[data-box-game]').forEach(function(root){ if(root.dataset.ready==='true')return; root.dataset.ready='true'; window.Lesson8Game.init(root); });
  const editor=document.getElementById('code-editor'); if(editor){ editor.readOnly=true; editor.style.opacity='.65'; }
})();
</script>`,
    initialCode: `<!-- Play the Box Model mini-game to unlock this module. -->`,
    hideVisualPanel: false,
    progress: 60,
    validator: function(code) { return code.includes("L8_M12_WIN"); }
};