window.Lessons.lesson8.modules[9] = {
    title: "10. Border Radius",
    body: `<section class="box-brief">
      <p class="box-kicker">Box Model Lab</p>
      <h3>Morph square to rounded.</h3>
      <p><strong>Goal:</strong> Round the corners to 30px.</p>
    </section>`,
    svg: ``,
    widgetCode: `<!-- INTERACTIVE MODULE -->
<style>
.box-brief{display:grid;gap:8px;padding:16px;border-radius:8px;background:#111827;border:1px solid rgba(103,232,249,.22);color:#dbeafe}.box-brief h3{margin:0;color:#f8fafc;font-size:21px}.box-brief p{margin:0;line-height:1.45}.box-kicker{color:#67e8f9;text-transform:uppercase;letter-spacing:.18em;font-size:11px;font-weight:800}
.box-game{display:grid;gap:14px;width:100%;padding:16px;border-radius:8px;background:linear-gradient(180deg,#101827,#172033);border:1px solid rgba(103,232,249,.25);color:#f8fafc;box-shadow:0 18px 38px rgba(0,0,0,.28)}
.box-hud{display:grid;gap:10px}.box-hud-row{display:flex;align-items:center;justify-content:space-between;gap:12px;flex-wrap:wrap}.box-title{font-family:Orbitron,sans-serif;color:#67e8f9;font-size:13px;letter-spacing:.14em;text-transform:uppercase}.box-stat{font:800 12px/1.2 Fira Code,monospace;color:#d1fae5}
.box-meter{height:10px;border-radius:999px;background:#273244;overflow:hidden;border:1px solid rgba(255,255,255,.08)}.box-meter span{display:block;height:100%;width:0;background:linear-gradient(90deg,#22c55e,#67e8f9);transition:width .25s ease}
.box-goal{padding:10px 12px;border-radius:8px;background:#e0f2fe;color:#0f172a;font-weight:900}.box-layout{display:grid;grid-template-columns:minmax(0,1.05fr) minmax(220px,.95fr);gap:12px}.box-stage{position:relative;min-height:290px;border-radius:8px;background:#f8fafc;color:#111827;padding:16px;overflow:hidden;display:grid;place-items:center;border:1px solid rgba(255,255,255,.18)}
.box-side{display:grid;gap:10px;align-content:start}.box-code{margin:0;min-height:112px;padding:12px;border-radius:8px;background:#07111f;color:#dbeafe;border:1px solid rgba(103,232,249,.22);font:800 13px/1.55 Fira Code,monospace;white-space:pre-wrap}.box-code mark{background:#facc15;color:#111827;border-radius:4px;padding:0 3px}.box-task{display:grid;gap:8px;padding:10px;border-radius:8px;background:#0b1220;border:1px solid rgba(103,232,249,.2)}
.box-task label{font-weight:900;color:#bfdbfe}.box-answer{display:block;padding:9px 10px;border-radius:8px;background:#ecfeff;color:#083344;border:1px solid #67e8f9;font:900 13px/1.45 Fira Code,monospace;box-shadow:0 0 0 2px rgba(103,232,249,.12)}.box-answer strong{display:block;margin-bottom:4px;color:#0f172a;font:900 11px/1.2 Orbitron,sans-serif;letter-spacing:.12em;text-transform:uppercase}.box-task-note{margin:0;padding:10px 12px;border-radius:8px;background:#020617;color:#cbd5e1;border:1px dashed rgba(103,232,249,.28);font:800 12px/1.5 Fira Code,monospace}
.box-controls{display:grid;gap:10px}.box-row{display:flex;gap:10px;flex-wrap:wrap;align-items:center;justify-content:center}.box-btn{border:0;border-radius:8px;padding:12px 14px;background:#2563eb;color:white;font-weight:900;cursor:pointer;transition:transform .15s ease,box-shadow .15s ease,background .15s ease}.box-btn:hover,.box-btn.selected{transform:translateY(-1px);box-shadow:0 0 18px rgba(37,99,235,.32)}.box-btn.good{background:#16a34a}.box-btn.bad{background:#dc2626}
.box-slider{width:min(280px,100%);accent-color:#2563eb}.box-feedback{min-height:36px;padding:10px 12px;border-radius:8px;background:#0b1220;border:1px solid rgba(103,232,249,.18);color:#bfdbfe;font-weight:800;text-align:center}.box-feedback.good{color:#86efac;border-color:#22c55e}.box-feedback.bad{color:#fecaca;border-color:#ef4444}
.box-demo{transition:all .2s ease;display:grid;place-items:center;text-align:center;font-weight:900}.target-outline{position:absolute;border:3px dashed #ef4444;border-radius:8px;pointer-events:none}.choice-card{padding:12px;border-radius:8px;background:white;border:2px solid #cbd5e1;cursor:pointer;font-weight:900;min-width:120px;text-align:center;transition:all .18s ease}.choice-card.selected{border-color:#2563eb;box-shadow:0 0 0 4px rgba(37,99,235,.12)}.choice-card.good{border-color:#16a34a;background:#dcfce7}.choice-card.bad{border-color:#dc2626;background:#fee2e2}.box-mission{display:grid;gap:10px;text-align:left}.box-step-list{margin:0;padding-left:18px;color:#1e293b;font-weight:900;line-height:1.5}.box-step-list code{background:#0f172a;color:#67e8f9;border-radius:5px;padding:2px 5px}
.box-confetti{position:absolute;width:8px;height:12px;background:#22c55e;animation:box-pop 720ms ease forwards}@keyframes box-pop{to{transform:translate(var(--x),var(--y)) rotate(540deg);opacity:0}}@media(max-width:800px){.box-layout{grid-template-columns:1fr}.box-stage{min-height:250px}.box-btn{width:100%}.choice-card{flex:1 1 140px}}
</style>
<div class="box-game" data-box-game data-config='{"marker":"L8_M10_WIN","index":10,"total":20,"kind":"singleSlider","goal":"Round the corners to 30px.","selector":".box","rules":[{"property":"border-radius","value":"30px"}],"options":[],"quiz":[]}'>
  <div class="box-hud">
    <div class="box-hud-row"><div class="box-title">Module 10 / 20</div><div class="box-stat" data-xp>XP 0</div><div class="box-stat" data-attempts>Attempts 0</div></div>
    <div class="box-meter"><span data-xp-bar></span></div>
    <div class="box-meter"><span data-progress-bar></span></div>
  </div>
  <div class="box-goal">Goal: Round the corners to 30px.</div>
  <div class="box-layout">
    <div class="box-stage" data-stage></div>
    <div class="box-side">
      <pre class="box-code" data-code></pre>
      <div class="box-task">
        <label data-task-label>Type this in INPUT CODE:</label>
        <span class="box-answer"><strong>Copy this CSS</strong>border-radius: 30px;</span>
        <p class="box-task-note">Use the mini-game, then type this CSS in INPUT CODE: border-radius: 30px;</p>
      </div>
    </div>
  </div>
  <div class="box-controls" data-controls></div>
  <div class="box-feedback" data-feedback>Use the mini-game, then type this CSS in INPUT CODE: border-radius: 30px;</div>
</div>
<script>
(function(){
  if(!window.Lesson8StrictGame){
    window.Lesson8StrictGame=(function(){
      const storeKey='lesson8-box-xp';
      const state={xp:Number(localStorage.getItem(storeKey)||0)};
      function sound(type){ window.lesson8LastSound=type; try{ const A=window.AudioContext||window.webkitAudioContext; if(!A)return; const ctx=new A(); const osc=ctx.createOscillator(); const gain=ctx.createGain(); osc.frequency.value=type==='success'?740:type==='error'?180:420; gain.gain.value=.035; osc.connect(gain); gain.connect(ctx.destination); osc.start(); setTimeout(function(){osc.stop();ctx.close();},90);}catch(e){} }
      function addXp(amount){ state.xp+=amount; localStorage.setItem(storeKey,String(state.xp)); }
      function cleanCssValue(value){ return String(value).trim().toLowerCase().split('').reduce(function(result,ch){ const isSpace=ch===' '||ch===String.fromCharCode(9)||ch===String.fromCharCode(10)||ch===String.fromCharCode(13); if(isSpace)return result.endsWith(' ')?result:result+' '; return result+ch; },'').trim(); }
      function ruleMatches(text,rule){ const expectedProperty=String(rule.property).trim().toLowerCase(); const expectedValue=cleanCssValue(rule.value); return String(text).split(';').some(function(part){ const colon=part.indexOf(':'); if(colon<0)return false; const property=part.slice(0,colon).split('{').pop().trim().toLowerCase(); const value=cleanCssValue(part.slice(colon+1)); return property===expectedProperty&&value===expectedValue; }); }
      function updateHud(root,cfg){ root.querySelector('[data-xp]').textContent='XP '+state.xp; root.querySelector('[data-xp-bar]').style.width=Math.min(100,state.xp%100)+'%'; root.querySelector('[data-progress-bar]').style.width=Math.round((cfg.index/cfg.total)*100)+'%'; root.querySelector('[data-attempts]').textContent='Attempts '+(root._attempts||0); }
      function setFeedback(root,text,mode){ const el=root.querySelector('[data-feedback]'); el.textContent=text; el.classList.toggle('good',mode==='good'); el.classList.toggle('bad',mode==='bad'); }
      function confetti(root){ const stage=root.querySelector('[data-stage]'); for(let i=0;i<26;i++){ const bit=document.createElement('i'); bit.className='box-confetti'; bit.style.left='50%'; bit.style.top='50%'; bit.style.background=['#22c55e','#67e8f9','#facc15','#fb7185'][i%4]; bit.style.setProperty('--x',(Math.random()*360-180)+'px'); bit.style.setProperty('--y',(Math.random()*-220-40)+'px'); stage.appendChild(bit); setTimeout(()=>bit.remove(),760); } }
      function renderCode(root,cfg){ const active=root._activeRule||cfg.rules[0]; const lines=[cfg.selector+' {'].concat(cfg.rules.map(function(rule){ const open=rule.property===active.property?'<mark>':''; const close=rule.property===active.property?'</mark>':''; return '  '+open+rule.property+': '+rule.value+';'+close;}),['}']); root.querySelector('[data-code]').innerHTML=lines.join(String.fromCharCode(10)); }
      function setRules(root,cfg,updates){ cfg.rules.forEach(function(rule){ if(Object.prototype.hasOwnProperty.call(updates,rule.property)){ rule.value=String(updates[rule.property]); root._activeRule=rule; }}); renderCode(root,cfg); }
      function attempt(root,cfg,msg,bad){ root._attempts=(root._attempts||0)+1; const decay=Math.max(1,5-Math.floor((root._attempts-1)/3)); addXp(decay); updateHud(root,cfg); setFeedback(root,msg+(bad?'':' (+'+decay+' XP)'),bad?'bad':''); sound(bad?'error':'click'); }
      function stage(root,content){root.querySelector('[data-stage]').innerHTML=content}
      function controls(root,content){root.querySelector('[data-controls]').innerHTML=content}
      function visualDone(root,cfg,msg){ root._visualDone=true; setFeedback(root,(msg||'Visual target solved.')+' Now type the CSS in INPUT CODE.','good'); confetti(root); sound('success'); }
      const games={
        clickBoxes:function(root,cfg){ stage(root,'<div class="box-mission"><ol class="box-step-list"><li>Click each webpage part to reveal its box.</li><li>Watch the outline appear around the header, picture, and button.</li><li>Then type <code>outline: 3px solid cyan;</code> in INPUT CODE.</li></ol><div style="display:grid;gap:14px;width:100%;max-width:310px;padding:16px;border-radius:12px;background:#dbeafe;border:2px solid #94a3b8"><div class="choice-card" data-box style="background:#bfdbfe">Header</div><div class="choice-card" data-box style="background:#fde68a;height:78px;display:grid;place-items:center">Picture</div><div class="choice-card" data-box style="background:#67e8f9">Button</div></div></div>'); controls(root,'<div class="box-task-note">Why this matters: CSS can style every webpage part because every element lives inside a box.</div>'); const clicked=new Set(); root.querySelectorAll('[data-box]').forEach(el=>el.onclick=()=>{clicked.add(el.textContent); el.classList.add('selected'); el.style.outline='3px solid #06b6d4'; setRules(root,cfg,{outline:'3px solid cyan'}); const left=3-clicked.size; if(left>0){attempt(root,cfg,'Box revealed: '+el.textContent+'. '+left+' more to inspect.');}else{attempt(root,cfg,'All 3 webpage parts are boxes. Now type the CSS in INPUT CODE.'); visualDone(root,cfg,'Everything on the page is built from boxes.');}});},
        borderSlider:function(root,cfg){ stage(root,'<div class="box-demo" data-demo style="width:160px;height:110px;background:#fef08a;border:0 solid red">I am a box</div>'); controls(root,'<label>Border thickness <input class="box-slider" data-range type="range" min="0" max="12" value="0"></label>'); const d=root.querySelector('[data-demo]'),r=root.querySelector('[data-range]'); r.oninput=()=>{d.style.borderWidth=r.value+'px'; setRules(root,cfg,{border:r.value+'px solid red'}); attempt(root,cfg,'Border: '+r.value+'px'); if(+r.value===8)visualDone(root,cfg,'Target border matched.');};},
        sizeMatch:function(root,cfg){ stage(root,'<div class="target-outline" style="width:180px;height:110px"></div><div class="box-demo" data-demo style="width:80px;height:60px;background:#93c5fd">Resize me</div>'); controls(root,'<label>Width <input class="box-slider" data-w type="range" min="60" max="240" value="80"></label><label>Height <input class="box-slider" data-h type="range" min="40" max="160" value="60"></label>'); const d=root.querySelector('[data-demo]'); function go(){const w=+root.querySelector('[data-w]').value,h=+root.querySelector('[data-h]').value; d.style.width=w+'px'; d.style.height=h+'px'; setRules(root,cfg,{width:w+'px',height:h+'px'}); attempt(root,cfg,w+' x '+h); if(w===180&&h===110)visualDone(root,cfg,'Target size matched.');} root.querySelector('[data-w]').oninput=go; root.querySelector('[data-h]').oninput=go;},
        singleSlider:function(root,cfg){ const rule=cfg.rules[0]; stage(root,'<div class="box-demo" data-demo style="background:#fb7185;border:3px solid #111827;max-width:220px">'+(rule.property==='border-radius'?'Round me':'Text needs space')+'</div>'); controls(root,'<label>'+rule.property+' <input class="box-slider" data-range type="range" min="0" max="'+(rule.value.includes('%')?'50':'60')+'" value="0"></label>'); const d=root.querySelector('[data-demo]'),r=root.querySelector('[data-range]'); r.oninput=()=>{const val=r.value+(rule.value.includes('%')?'%':'px'); d.style[rule.property.replace(/-([a-z])/g,function(_,c){return c.toUpperCase();})]=val; setRules(root,cfg,{[rule.property]:val}); attempt(root,cfg,rule.property+': '+val); if(val===rule.value)visualDone(root,cfg,'Target '+rule.property+' matched.');};},
        fourPadding:function(root,cfg){ stage(root,'<div class="box-demo" data-demo style="background:#fde68a;border:3px solid #111827;padding:2px">Fix all four sides</div>'); controls(root,['Top','Right','Bottom','Left'].map((n,i)=>'<label>'+n+' <input class="box-slider" data-pad="'+i+'" type="range" min="0" max="40" value="2"></label>').join('')); const d=root.querySelector('[data-demo]'); function go(){const v=[...root.querySelectorAll('[data-pad]')].map(x=>+x.value); d.style.padding=v.map(x=>x+'px').join(' '); setRules(root,cfg,{'padding-top':v[0]+'px','padding-right':v[1]+'px','padding-bottom':v[2]+'px','padding-left':v[3]+'px'}); attempt(root,cfg,'Padding: '+v.join(' / ')); if(v[0]===20&&v[1]===30&&v[2]===20&&v[3]===30)visualDone(root,cfg,'Specific padding fixed.');} root.querySelectorAll('[data-pad]').forEach(x=>x.oninput=go);},
        margin:function(root,cfg){ stage(root,'<div class="box-demo" data-a style="width:130px;height:74px;background:#14b8a6;color:white">Box 1</div><div class="box-demo" data-b style="width:130px;height:74px;background:#f97316;color:white;margin-top:-32px">Box 2</div>'); controls(root,'<label>Margin <input class="box-slider" data-range type="range" min="0" max="60" value="0"></label>'); const b=root.querySelector('[data-b]'),r=root.querySelector('[data-range]'); r.oninput=()=>{b.style.marginTop=r.value+'px'; setRules(root,cfg,{margin:r.value+'px'}); attempt(root,cfg,'Margin: '+r.value+'px'); if(+r.value===30)visualDone(root,cfg,'Overlap fixed with margin.');};},
        choices:function(root,cfg){ stage(root,'<div style="width:100%;background:#e2e8f0;padding:14px"><div class="box-demo" data-demo style="width:150px;height:80px;background:#f9a8d4">Choose the rule</div></div>'); controls(root,cfg.options.map(o=>'<button class="box-btn" data-value="'+o.value+'">'+o.label+'</button>').join('')); root.querySelectorAll('[data-value]').forEach(btn=>btn.onclick=()=>{ if(btn.dataset.value===cfg.rules[0].value){btn.classList.add('good'); setRules(root,cfg,{[cfg.rules[0].property]:btn.dataset.value}); const d=root.querySelector('[data-demo]'); d.style[ cfg.rules[0].property.replace(/-([a-z])/g,function(_,c){return c.toUpperCase();})]=btn.dataset.value; visualDone(root,cfg,'Correct CSS logic.');} else {btn.classList.add('bad'); attempt(root,cfg,'Try the rule that matches the goal.',true);} });},
        insideOutside:function(root,cfg){ stage(root,'<div class="box-demo" data-demo style="background:#fef08a;border:3px solid #111827;padding:2px;margin:2px">Text</div><div style="font-weight:900;color:#334155">Choose the space inside the border.</div>'); controls(root,'<button class="box-btn" data-value="20px">Padding is inside</button><button class="box-btn" data-value="outside">Margin is outside</button>'); const d=root.querySelector('[data-demo]'); root.querySelectorAll('[data-value]').forEach(btn=>btn.onclick=()=>{ if(btn.dataset.value==='20px'){d.style.padding='20px'; btn.classList.add('good'); setRules(root,cfg,{padding:'20px'}); visualDone(root,cfg,'Inside space is padding.');}else{btn.classList.add('bad'); d.style.margin='20px'; attempt(root,cfg,'That moves outside the border. Try inside.',true);} });},
        boxSizing:function(root,cfg){ stage(root,'<div style="width:230px;border:3px dashed #ef4444;padding:4px"><div class="box-demo" data-demo style="width:200px;padding:50px;background:#a78bfa;box-sizing:content-box">Too wide</div></div>'); controls(root,'<button class="box-btn" data-value="content-box">content-box</button><button class="box-btn" data-value="border-box">border-box</button>'); const d=root.querySelector('[data-demo]'); root.querySelectorAll('[data-value]').forEach(btn=>btn.onclick=()=>{ if(btn.dataset.value==='border-box'){d.style.boxSizing='border-box';d.textContent='Fixed width';btn.classList.add('good');setRules(root,cfg,{'box-sizing':'border-box'});visualDone(root,cfg,'border-box fixed the bug.');}else{btn.classList.add('bad');attempt(root,cfg,'content-box keeps padding outside the width.',true);} });},
        displayChoice:function(root,cfg){ stage(root,'<div style="width:100%;background:#e2e8f0;padding:14px"><div data-line-wrap><div class="display-item" style="display:block;width:86px;height:54px;margin:4px;background:#bbf7d0;border:2px solid #111827;text-align:center;font-weight:900">One</div><div class="display-item" style="display:block;width:86px;height:54px;margin:4px;background:#bfdbfe;border:2px solid #111827;text-align:center;font-weight:900">Two</div><div class="display-item" style="display:block;width:86px;height:54px;margin:4px;background:#fecaca;border:2px solid #111827;text-align:center;font-weight:900">Three</div></div></div>'); controls(root,cfg.options.map(o=>'<button class="box-btn" data-value="'+o.value+'">'+o.label+'</button>').join('')); root.querySelectorAll('[data-value]').forEach(btn=>btn.onclick=()=>{ const good=btn.dataset.value===cfg.rules[0].value; if(good){btn.classList.add('good'); root.querySelectorAll('.display-item').forEach(item=>{item.style.display=btn.dataset.value; item.style.verticalAlign='top';}); setRules(root,cfg,{display:btn.dataset.value}); visualDone(root,cfg,'The elements now share one line.');}else{btn.classList.add('bad'); attempt(root,cfg,'That still misses the target layout.',true);} });},
        quiz:function(root,cfg){ let q=0,score=0; stage(root,'<div class="choice-card" data-question></div>'); controls(root,'<div class="box-row" data-answers></div>'); function paint(){root.querySelector('[data-question]').textContent=cfg.quiz[q].q; root.querySelector('[data-answers]').innerHTML=cfg.quiz[q].a.map((x,i)=>'<button class="box-btn" data-i="'+i+'">'+x+'</button>').join(''); root.querySelectorAll('[data-i]').forEach(b=>b.onclick=()=>{ if(+b.dataset.i===cfg.quiz[q].c){score++; attempt(root,cfg,'Correct.');}else attempt(root,cfg,'Missed it. Keep going.',true); q++; if(q>=cfg.quiz.length){setRules(root,cfg,{[cfg.rules[0].property]:cfg.rules[0].value}); visualDone(root,cfg,'Quiz cleared: '+score+'/'+cfg.quiz.length);} else paint();});} paint();},
        shorthand:function(root,cfg){ const order=['top','right','bottom','left']; let step=0; stage(root,'<div class="box-demo" style="background:#fed7aa;border:3px solid #111827;padding:10px 20px 30px 40px">10 20 30 40</div>'); controls(root,order.map(x=>'<button class="box-btn" data-side="'+x+'">'+x+'</button>').join('')); root.querySelectorAll('[data-side]').forEach(b=>b.onclick=()=>{ if(b.dataset.side===order[step]){b.classList.add('good'); step++; attempt(root,cfg,'Clockwise.'); if(step===4){setRules(root,cfg,{padding:'10px 20px 30px 40px'}); visualDone(root,cfg,'Top, right, bottom, left decoded.');}}else attempt(root,cfg,'Follow top, right, bottom, left.',true);});},
        transparent:function(root,cfg){ stage(root,'<div class="box-demo" data-demo style="width:130px;height:100px;background:#fde68a;border:10px solid #111827">Ghost box</div><div style="margin-top:12px;color:#334155">It still occupies space.</div>'); controls(root,'<button class="box-btn" data-bg>Make background transparent</button><button class="box-btn" data-border>Make border transparent</button>'); const done={bg:false,border:false},d=root.querySelector('[data-demo]'); root.querySelector('[data-bg]').onclick=()=>{done.bg=true; d.style.background='transparent'; setRules(root,cfg,{background:'transparent'}); attempt(root,cfg,'Background vanished.'); if(done.border)visualDone(root,cfg,'Invisible, but still a box.');}; root.querySelector('[data-border]').onclick=()=>{done.border=true; d.style.borderColor='transparent'; setRules(root,cfg,{border:'10px solid transparent'}); attempt(root,cfg,'Border vanished.'); if(done.bg)visualDone(root,cfg,'Invisible, but still a box.');};},
        finalCard:function(root,cfg){ stage(root,'<div class="box-demo" data-demo style="width:230px;background:#ffffff;color:#111827;padding:4px;margin:0;border:0 solid #06b6d4;border-radius:0;box-shadow:0 10px 24px rgba(0,0,0,.16)"><strong>Nova Coder</strong><p>Box model badge</p></div>'); controls(root,'<label>Padding <input class="box-slider" data-pad type="range" min="0" max="28" value="4"></label><label>Margin <input class="box-slider" data-mar type="range" min="0" max="40" value="0"></label><label>Radius <input class="box-slider" data-rad type="range" min="0" max="24" value="0"></label><label>Border <input class="box-slider" data-bor type="range" min="0" max="6" value="0"></label>'); const d=root.querySelector('[data-demo]'); function go(){const p=+root.querySelector('[data-pad]').value,m=+root.querySelector('[data-mar]').value,r=+root.querySelector('[data-rad]').value,b=+root.querySelector('[data-bor]').value; d.style.padding=p+'px';d.style.margin=m+'px';d.style.borderRadius=r+'px';d.style.borderWidth=b+'px'; setRules(root,cfg,{padding:p+'px',margin:m+'px','border-radius':r+'px',border:b+'px solid cyan'}); attempt(root,cfg,'Card CSS updated.'); if(p===20&&m===20&&r===15&&b===2)visualDone(root,cfg,'Final card visual matched.');} root.querySelectorAll('input').forEach(x=>x.oninput=go);}
      };
      function init(root){ const cfg=JSON.parse(root.dataset.config); root._attempts=0; root._visualDone=false; updateHud(root,cfg); renderCode(root,cfg); setFeedback(root,'Use the mini-game to learn the rule, then type the CSS in INPUT CODE.',''); const fn=games[cfg.kind]; if(fn)fn(root,cfg); }
      return {init:init};
    })();
  }
  document.querySelectorAll('[data-box-game]').forEach(function(root){ if(root.dataset.ready==='true')return; root.dataset.ready='true'; window.Lesson8StrictGame.init(root); });
  const editor=document.getElementById('code-editor'); if(editor){ editor.readOnly=false; editor.style.opacity='1'; }
})();
</script>`,
    cssSelector: ".box",
    previewScaffold: `<div class="lesson8-css-preview" style="display:grid;gap:14px;padding:18px;border-radius:14px;background:#eef6ff;color:#0f172a;">
  <header class="box item" style="padding:12px;background:#bfdbfe;border:2px solid #1e293b;border-radius:8px;">Header box</header>
  <div class="box card ghost" style="width:150px;height:90px;display:grid;place-items:center;background:#fde68a;border:4px solid #0f172a;border-radius:4px;">Box card</div>
  <button class="box item" style="width:130px;padding:10px;background:#67e8f9;border:2px solid #0f172a;border-radius:8px;font-weight:900;">Button box</button>
</div>`,
    initialCode: `/* styles.css - type the CSS rule inside this selector */
.box {
  
}`,
    progress: 50,
    validator: function(code) {
      const rules = [{"property":"border-radius","value":"30px"}];
      function cleanCssValue(value) {
        return String(value).trim().toLowerCase().split('').reduce(function(result, ch) {
          const isSpace = ch === ' ' || ch === String.fromCharCode(9) || ch === String.fromCharCode(10) || ch === String.fromCharCode(13);
          if (isSpace) return result.endsWith(' ') ? result : result + ' ';
          return result + ch;
        }, '').trim();
      }
      function ruleMatches(text, rule) {
        const expectedProperty = String(rule.property).trim().toLowerCase();
        const expectedValue = cleanCssValue(rule.value);
        return String(text).split(';').some(function(part) {
          const colon = part.indexOf(':');
          if (colon < 0) return false;
          const property = part.slice(0, colon).split('{').pop().trim().toLowerCase();
          const value = cleanCssValue(part.slice(colon + 1));
          return property === expectedProperty && value === expectedValue;
        });
      }
      return code.includes("L8_M10_WIN") || rules.every(function(rule) { return ruleMatches(code, rule); });
    }
};