window.Lessons.lesson9.modules[19] = {
    title: "20. Final Flex Challenge",
    body: `<section class="box-brief">
      <p class="box-kicker">Flexbox Lab</p>
      <h3>Final Flex Challenge</h3>
      <p><strong>Goal:</strong> Build a responsive dashboard row.</p>
    </section>`,
    svg: ``,
    widgetCode: `<!-- FLEXBOX GAME MODULE -->
<style>
.flex-game{display:grid;gap:14px;width:100%;padding:16px;border-radius:10px;background:linear-gradient(160deg,#07111f,#172033 60%,#0f766e);border:1px solid rgba(45,212,191,.32);color:#ecfeff;box-shadow:0 18px 38px rgba(0,0,0,.3)}
.flex-hud{display:grid;gap:10px}.flex-row{display:flex;align-items:center;justify-content:space-between;gap:10px;flex-wrap:wrap}.flex-title{font-family:Orbitron,sans-serif;color:#67e8f9;font-size:13px;letter-spacing:.14em;text-transform:uppercase}.flex-stat{font:800 12px/1.2 Fira Code,monospace;color:#d1fae5}
.flex-meter{height:10px;border-radius:999px;background:#233044;overflow:hidden;border:1px solid rgba(255,255,255,.1)}.flex-meter span{display:block;height:100%;width:0;background:linear-gradient(90deg,#facc15,#2dd4bf,#38bdf8);transition:width .25s ease}
.flex-goal{padding:10px 12px;border-radius:8px;background:#ccfbf1;color:#0f172a;font-weight:900}.flex-layout{display:grid;grid-template-columns:minmax(0,1.05fr) minmax(230px,.95fr);gap:12px}.flex-stage{position:relative;min-height:300px;border-radius:10px;background:radial-gradient(circle at top,#f8fafc,#dbeafe);color:#0f172a;padding:16px;overflow:hidden;display:grid;place-items:center;border:1px solid rgba(255,255,255,.18)}
.flex-side{display:grid;gap:10px;align-content:start}.flex-code{margin:0;min-height:122px;padding:12px;border-radius:9px;background:#020617;color:#dbeafe;border:1px solid rgba(103,232,249,.25);font:800 13px/1.55 Fira Code,monospace;white-space:pre-wrap}.flex-code mark{background:#facc15;color:#111827;border-radius:4px;padding:0 3px}
.flex-task{display:grid;gap:8px;padding:10px;border-radius:9px;background:#0b1220;border:1px solid rgba(103,232,249,.2)}.flex-task label{font-weight:900;color:#bfdbfe}.flex-answer{display:block;padding:9px 10px;border-radius:8px;background:#ecfeff;color:#083344;border:1px solid #67e8f9;font:900 13px/1.45 Fira Code,monospace;box-shadow:0 0 0 2px rgba(103,232,249,.12)}.flex-answer strong{display:block;margin-bottom:4px;color:#0f172a;font:900 11px/1.2 Orbitron,sans-serif;letter-spacing:.12em;text-transform:uppercase}.flex-input{width:100%;box-sizing:border-box;border-radius:8px;border:2px solid #334155;background:#020617;color:white;padding:11px 12px;font:800 14px/1.4 Fira Code,monospace}.flex-input.ok{border-color:#22c55e}.flex-input.no{border-color:#ef4444}
.flex-controls{display:grid;gap:10px}.flex-btn{border:0;border-radius:10px;padding:12px 14px;background:#0f766e;color:white;font-weight:900;cursor:pointer;transition:transform .15s ease,box-shadow .15s ease,background .15s ease}.flex-btn:hover,.flex-btn.selected{transform:translateY(-1px);box-shadow:0 0 20px rgba(45,212,191,.38)}.flex-btn.good{background:#16a34a}.flex-btn.bad{background:#dc2626}
.flex-slider{width:min(300px,100%);accent-color:#0f766e}.flex-feedback{min-height:38px;padding:10px 12px;border-radius:9px;background:#0b1220;border:1px solid rgba(103,232,249,.18);color:#bfdbfe;font-weight:800;text-align:center}.flex-feedback.good{color:#86efac;border-color:#22c55e}.flex-feedback.bad{color:#fecaca;border-color:#ef4444}
.demo-lane{width:100%;min-height:190px;border:3px dashed #0f172a;border-radius:12px;padding:12px;background:rgba(255,255,255,.75);transition:all .2s ease}.demo-item{display:grid;place-items:center;width:70px;height:58px;border-radius:12px;background:#38bdf8;color:#082f49;font-weight:900;border:3px solid #0f172a;box-shadow:0 8px 0 rgba(15,23,42,.18);transition:all .2s ease}.demo-item.hot{background:#facc15}.demo-item.vip{background:#fb7185}.demo-item.power{background:#86efac}.demo-avatar{width:72px;height:72px;border-radius:50%;background:linear-gradient(135deg,#fb7185,#facc15);border:4px solid #0f172a}
.flex-confetti{position:absolute;width:8px;height:12px;background:#22c55e;animation:flex-pop 720ms ease forwards}@keyframes flex-pop{to{transform:translate(var(--x),var(--y)) rotate(540deg);opacity:0}}@media(max-width:800px){.flex-layout{grid-template-columns:1fr}.flex-stage{min-height:250px}.flex-btn{width:100%}}
</style>
<div class="flex-game" data-flex-game data-config='{"title":"20. Final Flex Challenge","goal":"Build a responsive dashboard row.","kind":"final","selector":".dashboard","rules":[{"property":"display","value":"flex"},{"property":"justify-content","value":"space-between"},{"property":"align-items","value":"center"},{"property":"gap","value":"20px"},{"property":"flex-wrap","value":"wrap"}],"index":20,"total":20,"marker":"L9_M20_WIN"}'>
  <div class="flex-hud">
    <div class="flex-row"><div class="flex-title">Module 20 / 20</div><div class="flex-stat" data-xp>XP 0</div><div class="flex-stat" data-attempts>Attempts 0</div></div>
    <div class="flex-meter"><span data-xp-bar></span></div>
    <div class="flex-meter"><span data-progress-bar></span></div>
  </div>
  <div class="flex-goal">Goal: Build a responsive dashboard row.</div>
  <div class="flex-layout">
    <div class="flex-stage" data-stage></div>
    <div class="flex-side">
      <pre class="flex-code" data-code></pre>
      <div class="flex-task">
        <label>Type the CSS that matches your fix:</label>
        <span class="flex-answer"><strong>Copy this CSS</strong>display: flex; justify-content: space-between; align-items: center; gap: 20px; flex-wrap: wrap;</span>
        <input class="flex-input" data-css-input spellcheck="false" autocomplete="off" aria-label="Type this CSS: display: flex; justify-content: space-between; align-items: center; gap: 20px; flex-wrap: wrap;" placeholder="display: flex; justify-content: space-between; align-items: center; gap: 20px; flex-wrap: wrap;">
      </div>
    </div>
  </div>
  <div class="flex-controls" data-controls></div>
  <div class="flex-feedback" data-feedback>Type this CSS: display: flex; justify-content: space-between; align-items: center; gap: 20px; flex-wrap: wrap;</div>
</div>
<script>
(function(){
  if(!window.Lesson9FlexGame){
    window.Lesson9FlexGame=(function(){
      const storeKey='lesson9-flex-xp';
      const state={xp:Number(localStorage.getItem(storeKey)||0)};
      function sound(type){ window.lesson9LastSound=type; try{ const A=window.AudioContext||window.webkitAudioContext; if(!A)return; const ctx=new A(); const osc=ctx.createOscillator(); const gain=ctx.createGain(); osc.frequency.value=type==='success'?780:type==='error'?170:430; gain.gain.value=.03; osc.connect(gain); gain.connect(ctx.destination); osc.start(); setTimeout(function(){osc.stop();ctx.close();},85);}catch(e){} }
      function addXp(amount){ state.xp+=amount; localStorage.setItem(storeKey,String(state.xp)); }
      function cleanCssValue(value){ return String(value).trim().toLowerCase().split('').reduce(function(result,ch){ const isSpace=ch===' '||ch===String.fromCharCode(9)||ch===String.fromCharCode(10)||ch===String.fromCharCode(13); if(isSpace)return result.endsWith(' ')?result:result+' '; return result+ch; },'').trim(); }
      function ruleMatches(text,rule){ const expectedProperty=String(rule.property).trim().toLowerCase(); const expectedValue=cleanCssValue(rule.value); return String(text).split(';').some(function(part){ const colon=part.indexOf(':'); if(colon<0)return false; const property=part.slice(0,colon).split('{').pop().trim().toLowerCase(); const value=cleanCssValue(part.slice(colon+1)); return property===expectedProperty&&value===expectedValue; }); }
      function typedOk(root,cfg){ const text=root.querySelector('[data-css-input]').value.trim(); return (cfg.targetRules||cfg.rules).every(function(rule){return ruleMatches(text,rule);}); }
      function updateHud(root,cfg){ root.querySelector('[data-xp]').textContent='XP '+state.xp; root.querySelector('[data-xp-bar]').style.width=Math.min(100,state.xp%100)+'%'; root.querySelector('[data-progress-bar]').style.width=Math.round((cfg.index/cfg.total)*100)+'%'; root.querySelector('[data-attempts]').textContent='Attempts '+(root._attempts||0); }
      function setFeedback(root,text,mode){ const el=root.querySelector('[data-feedback]'); el.textContent=text; el.classList.toggle('good',mode==='good'); el.classList.toggle('bad',mode==='bad'); }
      function confetti(root){ const stage=root.querySelector('[data-stage]'); for(let i=0;i<28;i++){ const bit=document.createElement('i'); bit.className='flex-confetti'; bit.style.left='50%'; bit.style.top='50%'; bit.style.background=['#22c55e','#67e8f9','#facc15','#fb7185'][i%4]; bit.style.setProperty('--x',(Math.random()*360-180)+'px'); bit.style.setProperty('--y',(Math.random()*-220-40)+'px'); stage.appendChild(bit); setTimeout(function(){bit.remove();},760); } }
      function renderCode(root,cfg){ const active=root._activeRule||cfg.rules[0]; const lines=[cfg.selector+' {'].concat(cfg.rules.map(function(rule){ const open=rule.property===active.property?'<mark>':''; const close=rule.property===active.property?'</mark>':''; return '  '+open+rule.property+': '+rule.value+';'+close;}),['}']); root.querySelector('[data-code]').innerHTML=lines.join(String.fromCharCode(10)); }
      function setRules(root,cfg,updates){ cfg.rules.forEach(function(rule){ if(Object.prototype.hasOwnProperty.call(updates,rule.property)){ rule.value=String(updates[rule.property]); root._activeRule=rule; }}); renderCode(root,cfg); }
      function attempt(root,cfg,msg,bad){ root._attempts=(root._attempts||0)+1; const decay=Math.max(1,5-Math.floor((root._attempts-1)/3)); addXp(decay); updateHud(root,cfg); setFeedback(root,msg+(bad?'':' (+'+decay+' XP)'),bad?'bad':''); sound(bad?'error':'click'); }
      function tryWin(root,cfg,msg){ const input=root.querySelector('[data-css-input]'); const ok=typedOk(root,cfg); input.classList.toggle('ok',ok); input.classList.toggle('no',!ok&&input.value.trim().length>0); if(!root._visualDone){ setFeedback(root,'Solve the visual target first, then type the CSS.','bad'); return; } if(!ok){ setFeedback(root,'Now type the matching CSS. Whitespace and uppercase are okay.','bad'); return; } if(root.dataset.won==='true')return; root.dataset.won='true'; addXp(10); updateHud(root,cfg); setFeedback(root,msg||'Perfect flex fix! Next module unlocked.','good'); sound('success'); confetti(root); window.completeModule(cfg.marker); }
      function stage(root,content){root.querySelector('[data-stage]').innerHTML=content}
      function controls(root,content){root.querySelector('[data-controls]').innerHTML=content}
      function visualDone(root,cfg,msg){ root._visualDone=true; setFeedback(root,msg||'Visual target solved. Type the CSS to lock it in.','good'); tryWin(root,cfg,msg); }
      function lane(items){ return '<div class="demo-lane" data-lane>'+items+'</div>'; }
      const three='<div class="demo-item">A</div><div class="demo-item hot">B</div><div class="demo-item">C</div>';
      const games={
        power:function(root,cfg){ stage(root,lane(three)); controls(root,'<button class="flex-btn" data-flex>Activate Flexbox</button>'); root.querySelector('[data-flex]').onclick=function(){ const l=root.querySelector('[data-lane]'); l.style.display='flex'; l.style.gap='10px'; setRules(root,cfg,{display:'flex'}); visualDone(root,cfg,'The stack snapped into a flex row.'); }; },
        choice:function(root,cfg){ stage(root,lane(three)); const laneEl=root.querySelector('[data-lane]'); laneEl.style.display='flex'; laneEl.style.minHeight='190px'; laneEl.style.gap='10px'; controls(root,cfg.options.map(function(value){return '<button class="flex-btn" data-value="'+value+'">'+value+'</button>';}).join('')); root.querySelectorAll('[data-value]').forEach(function(btn){btn.onclick=function(){ const value=btn.dataset.value; const targetRule=(cfg.targetRules||cfg.rules)[(cfg.targetRules||cfg.rules).length-1]; const property=targetRule.property; const target=targetRule.value; btn.classList.add(value===target?'good':'bad'); if(property==='justify-content')laneEl.style.justifyContent=value; if(property==='align-items')laneEl.style.alignItems=value; if(property==='flex-direction')laneEl.style.flexDirection=value; if(property==='flex-wrap'){ laneEl.innerHTML=three+three; laneEl.style.width='260px'; laneEl.style.flexWrap=value==='column'?'nowrap':value; } if(property==='order')root.querySelector('.vip').style.order=value; if(property==='align-self')root.querySelector('.hot').style.alignSelf=value; setRules(root,cfg,{[property]:value}); value===target?visualDone(root,cfg,'Target value locked in.'):attempt(root,cfg,'Not the target value yet.',true); }; }); if(cfg.rules[0].property==='order'){ laneEl.innerHTML='<div class="demo-item">A</div><div class="demo-item vip">VIP</div><div class="demo-item">C</div>'; } if(cfg.rules[0].property==='align-self'){ laneEl.style.alignItems='flex-start'; laneEl.innerHTML='<div class="demo-item">A</div><div class="demo-item hot">Solo</div><div class="demo-item">C</div>'; } },
        slider:function(root,cfg){ stage(root,lane(three)); const laneEl=root.querySelector('[data-lane]'); laneEl.style.display='flex'; laneEl.style.gap='0px'; const property=cfg.rules[0].property; if(property==='flex-basis'){ laneEl.querySelectorAll('.demo-item').forEach(function(item){item.style.flexBasis='80px';}); } controls(root,'<label>'+property+' <input class="flex-slider" data-range type="range" min="'+cfg.slider.min+'" max="'+cfg.slider.max+'" value="'+cfg.slider.min+'"></label>'); root.querySelector('[data-range]').oninput=function(e){ const value=e.target.value+cfg.slider.unit; if(property==='gap')laneEl.style.gap=value; if(property==='flex-basis')laneEl.querySelectorAll('.demo-item').forEach(function(item){item.style.flexBasis=value;}); setRules(root,cfg,{[property]:value}); attempt(root,cfg,property+': '+value); if(+e.target.value===cfg.slider.target)visualDone(root,cfg,'Slider hit the target.'); }; },
        grow:function(root,cfg){ stage(root,lane('<div class="demo-item">A</div><div class="demo-item power power-cell">Power</div><div class="demo-item">C</div>')); const laneEl=root.querySelector('[data-lane]'); laneEl.style.display='flex'; laneEl.style.gap='10px'; controls(root,'<button class="flex-btn" data-grow>Grow the power cell</button>'); root.querySelector('[data-grow]').onclick=function(){ root.querySelector('.power-cell').style.flexGrow='1'; setRules(root,cfg,{'flex-grow':'1'}); visualDone(root,cfg,'The power cell filled the extra space.'); }; },
        builder:function(root,cfg){ stage(root,'<div class="demo-lane nav" data-lane style="display:block"><div class="demo-item">Logo</div></div>'); controls(root,'<button class="flex-btn" data-step="links">Add links</button><button class="flex-btn" data-step="button">Add button</button><button class="flex-btn" data-step="flex">Place navbar</button>'); const done={links:false,button:false,flex:false}; root.querySelectorAll('[data-step]').forEach(function(btn){btn.onclick=function(){ const step=btn.dataset.step; done[step]=true; btn.classList.add('good'); const laneEl=root.querySelector('[data-lane]'); if(step==='links')laneEl.insertAdjacentHTML('beforeend','<div class="demo-item hot">Links</div>'); if(step==='button')laneEl.insertAdjacentHTML('beforeend','<div class="demo-item vip">Join</div>'); if(step==='flex'){ laneEl.style.display='flex'; laneEl.style.justifyContent='space-between'; laneEl.style.alignItems='center'; setRules(root,cfg,{display:'flex','justify-content':'space-between','align-items':'center'}); } attempt(root,cfg,'Navbar part added.'); if(done.links&&done.button&&done.flex)visualDone(root,cfg,'Navbar built with Flexbox.'); }; }); },
        shorthand:function(root,cfg){ const order=['grow','shrink','basis']; let step=0; stage(root,lane('<div class="demo-item hot" style="flex:1 1 150px">1 1 150px</div>')); const labels={grow:'1 grow',shrink:'1 shrink',basis:'150px basis'}; controls(root,order.map(function(name){return '<button class="flex-btn" data-part="'+name+'">'+labels[name]+'</button>';}).join('')); root.querySelectorAll('[data-part]').forEach(function(btn){btn.onclick=function(){ if(btn.dataset.part===order[step]){btn.classList.add('good'); step++; attempt(root,cfg,'Correct piece.'); if(step===3){setRules(root,cfg,{flex:'1 1 150px'}); visualDone(root,cfg,'Flex shorthand decoded.');}}else{btn.classList.add('bad'); attempt(root,cfg,'Use grow, shrink, basis order.',true);} }; }); },
        quiz:function(root,cfg){ let q=0,score=0; stage(root,'<div class="demo-lane"><div class="demo-item hot" data-question></div></div>'); controls(root,'<div class="flex-row" data-answers></div>'); function paint(){root.querySelector('[data-question]').textContent=cfg.quiz[q].q; root.querySelector('[data-answers]').innerHTML=cfg.quiz[q].a.map(function(answer,i){return '<button class="flex-btn" data-i="'+i+'">'+answer+'</button>';}).join(''); root.querySelectorAll('[data-i]').forEach(function(btn){btn.onclick=function(){ if(+btn.dataset.i===cfg.quiz[q].c){score++; attempt(root,cfg,'Correct.');}else{attempt(root,cfg,'Missed it, keep moving.',true);} q++; if(q>=cfg.quiz.length){ const updates={}; cfg.rules.forEach(function(rule){updates[rule.property]=rule.value;}); setRules(root,cfg,updates); visualDone(root,cfg,'Quiz cleared: '+score+'/'+cfg.quiz.length);}else paint(); }; }); } paint(); },
        debug:function(root,cfg){ stage(root,'<div class="demo-lane toolbar" data-lane><div class="demo-item">Save</div><div class="demo-item hot">Run</div><div class="demo-item">Share</div></div>'); const laneEl=root.querySelector('[data-lane]'); const done={display:false,align:false,gap:false}; controls(root,'<button class="flex-btn" data-fix="display">Turn on flex</button><button class="flex-btn" data-fix="align">Center buttons</button><button class="flex-btn" data-fix="gap">Add 16px gap</button>'); root.querySelectorAll('[data-fix]').forEach(function(btn){btn.onclick=function(){ const fix=btn.dataset.fix; done[fix]=true; btn.classList.add('good'); if(fix==='display'){laneEl.style.display='flex'; setRules(root,cfg,{display:'flex'});} if(fix==='align'){laneEl.style.alignItems='center'; setRules(root,cfg,{'align-items':'center'});} if(fix==='gap'){laneEl.style.gap='16px'; setRules(root,cfg,{gap:'16px'});} attempt(root,cfg,'Bug fixed: '+fix); if(done.display&&done.align&&done.gap)visualDone(root,cfg,'Toolbar debug complete.'); }; }); },
        profile:function(root,cfg){ stage(root,'<div class="demo-lane profile" data-lane><div class="demo-avatar"></div><div><strong>Nova Coder</strong><p>Flexbox pilot</p></div></div>'); const laneEl=root.querySelector('[data-lane]'); const done={display:false,align:false,gap:false}; controls(root,'<button class="flex-btn" data-fix="display">Make row</button><button class="flex-btn" data-fix="align">Center avatar</button><button class="flex-btn" data-fix="gap">Add breathing room</button>'); root.querySelectorAll('[data-fix]').forEach(function(btn){btn.onclick=function(){ const fix=btn.dataset.fix; done[fix]=true; btn.classList.add('good'); if(fix==='display'){laneEl.style.display='flex'; setRules(root,cfg,{display:'flex'});} if(fix==='align'){laneEl.style.alignItems='center'; setRules(root,cfg,{'align-items':'center'});} if(fix==='gap'){laneEl.style.gap='18px'; setRules(root,cfg,{gap:'18px'});} attempt(root,cfg,'Profile part fixed.'); if(done.display&&done.align&&done.gap)visualDone(root,cfg,'Profile layout complete.'); }; }); },
        final:function(root,cfg){ stage(root,lane('<div class="demo-item">Stats</div><div class="demo-item hot">Chart</div><div class="demo-item vip">Action</div><div class="demo-item power">Notes</div>')); const laneEl=root.querySelector('[data-lane]'); const done={display:false,justify:false,align:false,gap:false,wrap:false}; controls(root,'<button class="flex-btn" data-fix="display">display flex</button><button class="flex-btn" data-fix="justify">space-between</button><button class="flex-btn" data-fix="align">align center</button><button class="flex-btn" data-fix="gap">gap 20px</button><button class="flex-btn" data-fix="wrap">wrap</button>'); root.querySelectorAll('[data-fix]').forEach(function(btn){btn.onclick=function(){ const fix=btn.dataset.fix; done[fix]=true; btn.classList.add('good'); if(fix==='display'){laneEl.style.display='flex'; setRules(root,cfg,{display:'flex'});} if(fix==='justify'){laneEl.style.justifyContent='space-between'; setRules(root,cfg,{'justify-content':'space-between'});} if(fix==='align'){laneEl.style.alignItems='center'; setRules(root,cfg,{'align-items':'center'});} if(fix==='gap'){laneEl.style.gap='20px'; setRules(root,cfg,{gap:'20px'});} if(fix==='wrap'){laneEl.style.flexWrap='wrap'; setRules(root,cfg,{'flex-wrap':'wrap'});} attempt(root,cfg,'Dashboard upgrade: '+fix); if(done.display&&done.justify&&done.align&&done.gap&&done.wrap)visualDone(root,cfg,'Final dashboard complete.'); }; }); }
      };
      function init(root){ const cfg=JSON.parse(root.dataset.config); cfg.targetRules=cfg.rules.map(function(rule){return {property:rule.property,value:rule.value};}); root._attempts=0; root._visualDone=false; updateHud(root,cfg); renderCode(root,cfg); const input=root.querySelector('[data-css-input]'); setFeedback(root,input.getAttribute('aria-label')||'Solve the visual target, then type the CSS.',''); input.addEventListener('input',function(){tryWin(root,cfg);}); const fn=games[cfg.kind]; if(fn)fn(root,cfg); }
      return {init:init};
    })();
  }
  document.querySelectorAll('[data-flex-game]').forEach(function(root){ if(root.dataset.ready==='true')return; root.dataset.ready='true'; window.Lesson9FlexGame.init(root); });
  const editor=document.getElementById('code-editor'); if(editor){ editor.readOnly=false; editor.style.opacity='1'; }
})();
</script>`,
    cssSelector: ".dashboard",
    previewScaffold: `<div class="lesson9-css-preview" style="display:grid;gap:14px;padding:18px;border-radius:14px;background:#eefcf9;color:#0f172a;">
  <div class="row nav gallery toolbar profile dashboard" style="min-height:150px;padding:12px;border:3px dashed #0f172a;border-radius:12px;background:#ffffff;">
    <div class="card demo-item" style="width:70px;height:58px;display:grid;place-items:center;background:#38bdf8;border:3px solid #0f172a;border-radius:10px;font-weight:900;">A</div>
    <div class="card vip special power-cell" style="width:70px;height:58px;display:grid;place-items:center;background:#facc15;border:3px solid #0f172a;border-radius:10px;font-weight:900;">B</div>
    <div class="card" style="width:70px;height:58px;display:grid;place-items:center;background:#fb7185;border:3px solid #0f172a;border-radius:10px;font-weight:900;">C</div>
  </div>
</div>`,
    initialCode: `/* styles.css - type the CSS rule inside this selector */
.dashboard {
  
}`,
    progress: 100,
    validator: function(code) {
      const rules = [{"property":"display","value":"flex"},{"property":"justify-content","value":"space-between"},{"property":"align-items","value":"center"},{"property":"gap","value":"20px"},{"property":"flex-wrap","value":"wrap"}];
      function cleanCssValue(value) {
        return String(value).trim().toLowerCase().split('').reduce(function(result, ch) {
          const isSpace = ch === ' ' || ch === String.fromCharCode(9) || ch === String.fromCharCode(10) || ch === String.fromCharCode(13);
          if (isSpace) return result.endsWith(' ') ? result : result + ' ';
          return result + ch;
        }, '').trim();
      }
      function ruleMatches(text, rule) {
        const expectedProperty = String(rule.property).trim().toLowerCase();
        const expectedValue = cleanCssValue(rule.value);
        return String(text).split(';').some(function(part) {
          const colon = part.indexOf(':');
          if (colon < 0) return false;
          const property = part.slice(0, colon).split('{').pop().trim().toLowerCase();
          const value = cleanCssValue(part.slice(colon + 1));
          return property === expectedProperty && value === expectedValue;
        });
      }
      return code.includes("L9_M20_WIN") || rules.every(function(rule) { return ruleMatches(code, rule); });
    }
};